### DISCUSSION TITLE
Support colors with alpha values

### DISCUSSION THREAD

**Discussion by RyanClementsHax** [RyanClementsHax/tailwindcss-themer#95] [Ideas]
Below is the feature request for supporting colors with alpha values when theming. I'd love feedback from the community before implementing this feature. Here are all of my thoughts so far. Let me know what y'all think and if there are any other implementations we could consider.

## Background
Currently this plugin [strips the alpha channel](https://github.com/RyanClementsHax/tailwindcss-themer/blob/0dc0042b322d37fe13317a9662bef2c5a469debe/docs/themingColors.md#opacity) from any color it is configured to theme. This is to support tailwind's opacity classes.

For example, if you use a class like `text-gray-50`, a default tailwind class, the following class gets generated.
```css
.text-gray-50 {
  --tw-text-opacity: 1;
  color: rgb(249 250 251 / var(--tw-text-opacity))
}
```

Tailwind then is able to control the opacity with `--tw-text-opacity`. For example, the class `text-opacity-50` would generate the following class.
```css
.text-opacity-50 {
  --tw-text-opacity: 0.5
}
```

`tailwindcss-themer` tries to honor this feature. For example, if you have a plugin config like the following....
```js
require('tailwindcss-themer')({
  defaultTheme: {
    extend: {
      colors: {
        primary: '#fff'
      }
    }
  },
  themes: [
    {
      name: 'darkMode',
      extend: {
        colors: {
          primary: '#000'
        }
      }
    }
  ]
})
```
....and use a class like `text-primary`, the following classes will be generated.
```css
:root {
  --colors-primary: 255, 255, 255;
}

.darkMode {
    --colors-primary: 0, 0, 0;
}

.text-primary {
  --tw-text-opacity: 1;
  color: rgba(var(--colors-primary), var(--tw-text-opacity));
}
```

This allows colors to be themed and opacity classes to work. This plugin, as a result, needs to [strip the alpha value from the specified color](https://github.com/RyanClementsHax/tailwindcss-themer/blob/0dc0042b322d37fe13317a9662bef2c5a469debe/docs/themingColors.md#opacity) for this to work as there is no way to configure the `--tw-text-opacity` variable (to the best of my knowledge).

## Problem
There are real use cases for using `tailwindcss-themer` with colors with alpha values, but tailwind's doesn't allow for the default opacity value of colors to be specified. In other words:
```css
.bg-gray-50 {
  --tw-bg-opacity: 1; /* 👈🏻 this can't be configured */
  background-color: rgb(249 250 251 / var(--tw-bg-opacity))
}
```
This thereby forces devs to choose between having a themed color that uses the alpha channel and that color's opacity being configurable via tailwind's [opacity classes](https://tailwindcss.com/docs/opacity).

### Color palettes with alpha values
Some devs want to use palettes with that use alpha values like [radix ui colors](https://www.radix-ui.com/colors/docs/palette-composition/scales) as exemplified in #74.

### `transparent`
Some devs want to have `transparent` be a theme value as exemplified in #77.

### (Preferred) Use the [opacity modifier syntax](https://tailwindcss.com/docs/upgrade-guide#new-opacity-modifier-syntax).

Configure the default opacity value by using a value like `rgb(255 0 0 / <alpha-value>)` for all colors without alpha channels and replace `<alpha-value>` with the alpha channel value for colors with alpha e.g. `rgb(255 0 0 / 0.5)`. [The docs unfortunately don't reflect this](https://github.com/tailwindlabs/tailwindcss/discussions/10347#discussioncomment-4710879), but this is a supported behavior.

Pros:
- Implements all functionality cleanly
- No need to make commits upstream

Cons:
- Needs a major version bump
- Doesn't support older classes like [bg-opacity-50](https://v2.tailwindcss.com/docs/background-opacity), but [they're deprecated](https://tailwindcss.com/docs/upgrade-guide#new-opacity-modifier-syntax)

### ~~(Preferred)~~ Work with tailwind upstream to allow this to be configurable

This would entail getting this committed upstream so this plugin could configure that value.

Pros:
- Few surprises i.e. colors with alpha channels "just work"

Cons:
- Takes a while
- No guarantee this will be accepted

### Silently opt out of opacity classes when a color with an alpha channel is given

This would mean that this plugin preserves the alpha channel but doesn't allow that color to be configurable via opacity classes.

Pros:
- Simple, quick change to this plugin

Cons:
- Opportunity for devs to be "surprised" when opacity classes don't work

## Resolution

Setting the default opacity value is supported via the [opacity modifier syntax](https://tailwindcss.com/docs/upgrade-guide#new-opacity-modifier-syntax). [The docs unfortunately don't reflect this](https://github.com/tailwindlabs/tailwindcss/discussions/10347#discussioncomment-4710879) which is why this took longer than expected to implement.

PR: https://github.com/RyanClementsHax/tailwindcss-themer/pull/111
